steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/dtumlops-374721/mlops-mnist-project", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/dtumlops-374721/mlops-mnist-project"]
