wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1673400329.187184
    t:
      1:
      - 1
      - 15
      - 55
      2:
      - 1
      - 15
      - 55
      3:
      - 1
      - 23
      4: 3.9.7
      5: 0.13.8
      8:
      - 5
